tasks:
  - name: aws-cli
    env: 
       AWS_CLI_AUTO_PROMPT: on-partial
    init: 
      HISTFILE=/workspace/.gitpod/cmd-0 history -r; {
      cd /workspace
      curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      unzip awscliv2.zip
      sudo ./aws/install
      cd $THEIA_WORKSPACE_ROOT}
vscode:
  extensions:
    - 42Crunch.vscode-openapi